FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir kafka-python

COPY . .

EXPOSE 3006

CMD ["python", "-m", "ml1m.gateway"]
